"use client";

import { useMemo, useState, type FormEvent } from "react";
import { RotateCcw, Search, ShieldCheck } from "lucide-react";
import { Alert } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Skeleton } from "@/components/ui/skeleton";
import {
  DEMO_DISCLAIMER,
  type SearchResponse,
  type SearchResult,
} from "@/lib/search/types";
import { LimitationAlert, SyntheticDisclaimer } from "@/components/perturb/primitives";

const examples = [
  "altered mitochondrial organization",
  "lysosomal stress phenotype",
  "disrupted cytoskeletal organization",
  "reduced nuclear texture",
  "increased cellular granularity",
];

export function DemoSearch() {
  const [query, setQuery] = useState(examples[0]);
  const [response, setResponse] = useState<SearchResponse | null>(null);
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);
  const canSubmit = useMemo(() => query.trim().length > 0 && query.length <= 240, [query]);

  async function submit(event?: FormEvent<HTMLFormElement>) {
    event?.preventDefault();
    setError("");
    setResponse(null);
    setLoading(true);
    try {
      const result = await fetch("/api/search", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ query }),
      });
      const payload = await result.json();
      if (!result.ok) {
        setError(payload.error ?? "Search failed.");
        return;
      }
      setResponse(payload);
    } catch {
      setError("The illustrative search service is unavailable.");
    } finally {
      setLoading(false);
    }
  }

  function reset() {
    setQuery("");
    setResponse(null);
    setError("");
  }

  return (
    <div className="grid gap-6 lg:grid-cols-[1fr_340px]">
      <Card className="card-paper shadow-none">
        <SyntheticDisclaimer />
        <h1 className="mt-5 text-4xl font-semibold leading-tight">
          Text-to-morphology search
        </h1>
        <p className="mt-4 text-ink/70">
          Submit a phenotype-style query. Results are anonymized, synthetic UI fixtures
          generated by a mock provider through the same API contract the real model will use later.
        </p>
        <form className="mt-8 space-y-4" onSubmit={submit}>
          <label className="text-sm font-semibold text-ink" htmlFor="demo-query">
            Biological phenotype query
          </label>
          <Input
            id="demo-query"
            value={query}
            onChange={(event) => setQuery(event.target.value)}
            placeholder="e.g. altered mitochondrial organization"
            aria-describedby="query-help"
          />
          <p id="query-help" className="text-xs text-ink/55">
            Queries are not stored. Keep this demo to broad biological concepts.
          </p>
          <div className="flex flex-wrap gap-2">
            {examples.map((example) => (
              <button
                key={example}
                type="button"
                className="rounded-full border border-ink/10 bg-white/70 px-3 py-1.5 text-xs font-semibold text-ink/70 transition hover:bg-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-teal"
                onClick={() => {
                  setQuery(example);
                  setResponse(null);
                  setError("");
                }}
              >
                {example}
              </button>
            ))}
          </div>
          <div className="flex flex-wrap gap-3">
            <Button disabled={!canSubmit || loading} type="submit">
              <Search className="h-4 w-4" /> Submit query
            </Button>
            <Button variant="secondary" type="button" onClick={reset}>
              <RotateCcw className="h-4 w-4" /> Reset
            </Button>
          </div>
        </form>
      </Card>

      <aside aria-label="Demo notes" className="space-y-4">
        <LimitationAlert>
          <div className="font-semibold">Synthetic output</div>
          <p className="mt-1">
            {DEMO_DISCLAIMER}. No live model is running. No real CPJUMP1 rows are queried.
          </p>
        </LimitationAlert>
        <Alert>
          <div className="flex gap-3">
            <ShieldCheck className="mt-0.5 h-5 w-5 text-teal" />
            <div>
              <div className="font-semibold">Leakage status</div>
              <p className="mt-1 text-ink/65">
                No treatment identifiers, target sequences, plate labels, or well
                labels are used in this illustrative demo.
              </p>
            </div>
          </div>
        </Alert>
        <Card className="card-soft shadow-none">
          <h2 className="font-display text-base font-semibold text-ink">
            What a real result would need
          </h2>
          <ul className="mt-3 list-disc space-y-2 pl-5 text-sm leading-6 text-ink/65">
            <li>Model-computed relevance under a stated leakage regime.</li>
            <li>Aggregate morphology evidence, never row-level fields.</li>
            <li>Broad feature-family summaries instead of raw feature dumps.</li>
            <li>Explicit split and filter context.</li>
          </ul>
        </Card>
      </aside>

      <div aria-live="polite" className="space-y-4 lg:col-start-1 lg:row-start-2" aria-busy={loading}>
        {loading ? <LoadingResults /> : null}
        {error ? <Alert className="border-red-200 bg-red-50 text-red-900">{error}</Alert> : null}
        {!loading && !error && !response ? (
          <Card className="text-sm text-ink/65">
            Submit a broad phenotype query to see synthetic ranked results.
          </Card>
        ) : null}
        {response ? (
          <>
            <p className="text-sm font-semibold text-ink">{response.disclaimer}</p>
            {response.results.map((result, index) => (
              <ResultCard key={result.id} result={result} rank={index + 1} />
            ))}
          </>
        ) : null}
      </div>
    </div>
  );
}

function LoadingResults() {
  return (
    <div className="space-y-3">
      <Skeleton className="h-28" />
      <Skeleton className="h-28" />
      <Skeleton className="h-28" />
    </div>
  );
}

function ResultCard({ result, rank }: { result: SearchResult; rank: number }) {
  return (
    <Card className="card-paper shadow-none">
      <div className="flex items-start justify-between gap-4">
        <div>
          <div className="text-sm font-semibold text-teal">Rank {rank}</div>
          <h2 className="mt-1 text-xl font-semibold">{result.label}</h2>
          <p className="mt-2 text-sm leading-6 text-ink/65">{result.description}</p>
        </div>
        <div
          className="rounded-md bg-ink px-3 py-2 text-sm font-semibold text-white"
          title="Illustrative score from mock synthetic tags, not a real model confidence."
        >
          {result.score.toFixed(3)}
        </div>
      </div>
      <div className="mt-4 flex flex-wrap gap-2">
        <Badge className="bg-amber-50 text-amber-900">synthetic result</Badge>
        <Badge className="bg-teal/10 text-teal">mock provider</Badge>
        {result.evidenceTags.map((tag) => (
          <Badge key={tag}>{tag}</Badge>
        ))}
      </div>
      <p className="mt-4 text-sm leading-6 text-ink/70">{result.morphologySummary}</p>
      <p className="mt-2 text-xs text-ink/50">{result.explanation}</p>
    </Card>
  );
}
